# Generated by Django 3.2 on 2021-06-18 12:55

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
