# Generated by Django 3.2 on 2021-05-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210519_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='dislike_btn_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_btn_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
