# Generated by Django 3.2 on 2021-06-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='product_name')),
                ('description', models.TextField(verbose_name='Description')),
                ('qty_in_stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False, help_text='This product will sell?')),
                ('type', models.CharField(choices=[('JPEG', 'normal quality'), ('PSD', 'photoshop file'), ('AI', 'illustrator'), ('TEXT', 'word file'), ('PRINT', 'print on paper')], max_length=100)),
            ],
        ),
    ]
